# Edge ConfigMap 
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-edge-runtime
  namespace: edge-deployment
data:
  SAG_IS_CLOUD_REGISTER_TOKEN: d7e4d4a52bd64bdca3d0249f275589fbeb93727097e94702a37f7cf94d290d5d
  SAG_IS_CLOUD_REGISTER_URL: https://wmintanywhere.int-aw-au.webmethods.io
  SAG_IS_EDGE_CLOUD_ALIAS: EdgeRuntime_SE_tlundstr_demo2
  SAG_IS_HEALTH_ENDPOINT_ACL: Anonymous
  SAG_IS_CLOUD_ALLOWSYNC: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-is
  namespace: "edge-deployment"
data:
  application.properties: |
    healthindicators.Adapters.enabled=true
    healthindicators.Cluster.enabled=true
    healthindicators.Cluster.properties.threshold.value=2
    healthindicators.Diskspace.enabled=true
    healthindicators.Diskspace.properties.threshold.value=10
    healthindicators.JDBC.enabled=true
    healthindicators.JMS.enabled=true
    healthindicators.JNDIAliases.enabled=false
    healthindicators.Memory.enabled=true
    healthindicators.Memory.properties.threshold.value=10
    healthindicators.RemoteServers.enabled=true
    healthindicators.SFTPServers.enabled=true
    healthindicators.ServiceThread.enabled=true
    healthindicators.ServiceThread.properties.threshold.value=10
    healthindicators.Sessions.enabled=true
    healthindicators.Sessions.properties.threshold.value=85
    healthindicators.UMAliases.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://universalmessaging.swag-infra\:9000
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "${CONTAINER}"
  namespace: "edge-deployment"
  labels:
    app: "${CONTAINER}"
spec:
  selector:
    matchLabels:
      app: "${CONTAINER}" 
  template: 
    metadata:
      labels:
        app: "${CONTAINER}"
    spec:
      containers:
        - name: "${CONTAINER}"
          image: "${IMAGENAME}"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: demo-edge-runtime
                optional: false
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 5555
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20      
  replicas: 1